//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOAEntities1 : DbContext
    {
        public SOAEntities1()
            : base("name=SOAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblArac> tblArac { get; set; }
        public virtual DbSet<tblKiralama> tblKiralama { get; set; }
        public virtual DbSet<tblMüsteri> tblMüsteri { get; set; }
        public virtual DbSet<tblPuan> tblPuan { get; set; }
        public virtual DbSet<tblSirket> tblSirket { get; set; }
        public virtual DbSet<tblTalep> tblTalep { get; set; }
    }
}
