//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArac()
        {
            this.tblKiralama = new HashSet<tblKiralama>();
            this.tblTalep = new HashSet<tblTalep>();
        }
    
        public int aracID { get; set; }
        public string aracMarka { get; set; }
        public string aracModel { get; set; }
        public Nullable<int> minEhliyetYasi { get; set; }
        public Nullable<int> minSürücüYasi { get; set; }
        public Nullable<int> günlükKmSiniri { get; set; }
        public Nullable<int> aracKmsi { get; set; }
        public Nullable<int> günlükKiralamaFiyati { get; set; }
        public Nullable<int> koltukSayisi { get; set; }
        public Nullable<int> yakitTürü { get; set; }
        public string aracFotograf { get; set; }
        public string aracAciklama { get; set; }
        public Nullable<int> kiralamaDurumu { get; set; }
        public string airbagDurumu { get; set; }
        public Nullable<int> sirketID { get; set; }
        public string aracKasaTipi { get; set; }
    
        public virtual tblSirket tblSirket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKiralama> tblKiralama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTalep> tblTalep { get; set; }
    }
}
