//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMüsteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMüsteri()
        {
            this.tblKiralama = new HashSet<tblKiralama>();
            this.tblTalep = new HashSet<tblTalep>();
        }
    
        public int müsteriID { get; set; }
        public string müsteriAdi { get; set; }
        public string müsteriSoyadi { get; set; }
        public string müsteriEmail { get; set; }
        public string müsteriPassword { get; set; }
        public Nullable<int> müsteriYasi { get; set; }
        public Nullable<System.DateTime> müsteriEhliyetTarihi { get; set; }
        public string müsteriSehir { get; set; }
        public string müsteriAdres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKiralama> tblKiralama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTalep> tblTalep { get; set; }
    }
}
