//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPuan
    {
        public int puanID { get; set; }
        public Nullable<int> müsteriID { get; set; }
        public Nullable<int> sirketID { get; set; }
        public Nullable<int> puan { get; set; }
    }
}
