//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracKiralama.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSirket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSirket()
        {
            this.tblArac = new HashSet<tblArac>();
            this.tblKiralama = new HashSet<tblKiralama>();
            this.tblTalep = new HashSet<tblTalep>();
        }
    
        public int sirketID { get; set; }
        public string sirketAdi { get; set; }
        public string sirketEmail { get; set; }
        public string sirketPassword { get; set; }
        public string sirketSehir { get; set; }
        public string sirketAdres { get; set; }
        public Nullable<int> aracSayisi { get; set; }
        public Nullable<int> sirketPuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArac> tblArac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKiralama> tblKiralama { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTalep> tblTalep { get; set; }
    }
}
